### ISSUE TITLE
readme.md: URLs broken for 7.6.1 and 7.6.2

### ISSUE THREAD

**Issue by kalnode** [johtani/analyze-api-ui-plugin#47]
readme.md: URLs broken for 7.6.1 and 7.6.2

In the URL, just the version number directly after "download/" needs to be changed:

https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.6.0/analyze_api_ui-7.6.2.zip

Should be:
https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.6.2/analyze_api_ui-7.6.2.zip

... and ...

https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.6.0/analyze_api_ui-7.6.1.zip

Should be:
https://github.com/johtani/analyze-api-ui-plugin/releases/download/7.6.1/analyze_api_ui-7.6.1.zip

**Comment by johtani** [comment]
@TheMangoTrain thank you for raising the issue!
Updated it.
