### ISSUE TITLE
No longer works with Kibana (+7.10); needs to use the Plugin API

### ISSUE THREAD

**Issue by kalnode** [johtani/analyze-api-ui-plugin#48]
This plugin no longer works with Kibana, doh!

Starting with Kibana 7.10, plugins need to use their new plugin API. Legacy plugins are no longer supported.

Plugin API docs:
https://www.elastic.co/guide/en/kibana/current/kibana-platform-plugin-api.html

Blog post (June 2020):
https://www.elastic.co/blog/introducing-a-new-architecture-for-kibana

Migration guide:
https://www.elastic.co/guide/en/kibana/current/migrating-legacy-plugins.html

**Comment by risdenk** [comment]
FWIW I have an almost working migration of this:

* https://github.com/risdenk/analyze-api-ui-plugin/tree/7.16.2
* https://github.com/risdenk/analyze-api-ui-plugin/releases/tag/v7.16.2-alpha5

So far this is working after fixing some of the rough edges.

**Comment by risdenk** [comment]
This is fixed in PR #49

**Comment by johtani** [comment]
Released 7.16.2 !
https://github.com/johtani/analyze-api-ui-plugin/tree/7.16.2

Thank @risdenk for your great help!!
